sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LZuPeecBDoGaqLIkI/+GGzNqblX2983bzgEHvwZiYpt6mXlrXyI0K4GtVXSu1dLG/dNziaJ56s4TrKiX73FcwPRFKGrZ3zzIupdr/J0mRq7odMUrXALwsYjFTK6Ra4vp+OmnxIUZKWch4OcKotjZyS04XXgU7VDr0uD+qGFPpzlsj+Pvgpj61JHprxOtYxml4Nf7KbE440SJV5J8M/rkcW2y3FhvRJi6gGDet4fgSNEx+LYgfH4MN1BB5lJy2jiIspKKocucXk4piskiDm3oZ2az+BAd5ihnTTMOwcabern18M0U+4ay/JUtEuqwm7sGpaNR0Gx0cl3zk57ChK/fWXGHlRLcMDv4RaM1g0bmbkqkWjjsMA4F+UyDxPkwVz/ni3GS6ajuBe87wb2P94HAda/jcrcuGlMYAQkima+AbnjGjsuyUJXHGyk1Ac8Wk30eCKHnWyVr/euLUbu7BFlsTg0oojlOstOqbFhBLzpSHbqRlUXQt/to9jt8ccbZFZk1bUrcX6OjkXqEiWS1NiPwaBWjsIUN1HPHQifZJ0UebvVDwfq8MuhlvzGRWdiAQG4j73jYp62YCMVoc76E7OLCCn1HEOsC2+cClupvblE/Ku75YZujHBfNilu6h0lDZuGBVgMiwzyaa1Jm2iTGUFG8JPz5ZCotK3nrucjygAQuX0o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Man-from-Snowy-River_213
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy